GET http://localhost:5097/
###

POST http://localhost:5097/api/v1/Login/Login HTTP/1.1
content-Type: application/json

{
    "Username": "admin1",
    "Password": "password"
}
###

POST http://localhost:5097/api/v1/Login/Register HTTP/1.1
Content-Type: application/json

{
    "Username":"Aicon",
    "Email": "user1@example.com",
    "Password":"password",
    "FirstName": "Aicon",
    "LastName": "Yan"
}
###

GET http://localhost:5097/api/v1/Login/IsAdminLoggedIn
###

GET http://localhost:5097/api/v1/Login/Logout
###