### Application Initialization Test 
GET http://localhost:5097/

### login POST test – Authenticate Admin or User
POST http://localhost:5097/api/v1/Login/Login
content-Type: application/json

{
    "Username": "admin1",
    "Password": "password"
}

### ⁠login/status GET test – Check Admin Login/Logout Status and Retrieve Name
POST http://localhost:5097/api/v1/Login/Register HTTP/1.1
Content-Type: application/json

{
    "Username":"Ben",
    "Email": "user2@example.com",
    "Password":"password2",
    "FirstName": "Ben",
    "LastName": "Son"
}
###

GET http://localhost:5097/api/v1/Login/IsAdminLoggedIn
### 
GET http://localhost:5097/api/v1/Login/Logout


### Events GET test – Retrieve All Events (Limited Functionality Due to Missing Database)
GET http://localhost:5097/api/v1/Event/GetAllEvents
Accept: application/json


### Event POST test - POST /events – Create New Event (To Be Tested with Postman; Limited Functionality Due to Missing Database)
POST http://localhost:5097/api/v1/Event/events
content-Type: application/json
Authorization: Bearer {jwt_token} 

{
    "Title": "New Event",
    "Description": "This is a new event created for testing purposes.",
    "EventDate": "2024-12-01",
    "StartTime": "10:00:00",
    "EndTime": "12:00:00",
    "Location": "Online"
}


### Event PUT test - Update Existing Event
PUT http://localhost:5097/api/v1/Event/UpdateEvent/1
content-Type: application/json
Authorization: Bearer {jwt_token}

{
    "Title": "Updated Event",
    "Description": "This event has been updated for testing purposes.",
    "EventDate": "2024-12-10",
    "StartTime": "14:00:00",
    "EndTime": "16:00:00",
    "Location": "Main Hall"
}

### Event DELETE test - Delete Event
DELETE http://localhost:5097/api/v1/Event/DeleteEvent/1
Authorization: Bearer {jwt_token}
###

### Add attendance for a user to an event
POST http://localhost:5000/api/v1/Event/Attendance?eventId=1&userId=1
Content-Type: application/json

###

### Get attendees for a specific event
GET http://localhost:5000/api/v1/Event/1/attendees
Authorization: Bearer {jwt_token}
###

### DELETE attendance for a user to an event
DELETE http://localhost:5000/api/v1/Event/1/attendees/1
Authorization: Bearer {jwt_token}
###

### Delete Attendance for Specific Event
DELETE http://localhost:5097/api/v1/Event/{eventId}/attendees/{userId}
Authorization: Bearer {jwt_token}
###

### Add Attendance
POST http://localhost:5097/api/v1/AttendanceModification/AddAttendance?eventId=1
Authorization: Bearer {jwt_token}
###

### Update Attendance
PUT http://localhost:5097/api/v1/AttendanceModification/UpdateAttendance?attendanceId=1&newDate=2024-10-15T09:00:00
Authorization: Bearer {jwt_token}
###

### Delete Attendance
DELETE http://localhost:5097/api/v1/AttendanceModification/DeleteAttendance/1
Authorization: Bearer {jwt_token}
###